version: "3"

services:
  #WEB PHP E APACHE
  web:
    image: webdevops/php-apache:7.4-alpine
    container_name: ${WEB_CONTAINER_NAME}
    ports:
      - "80:80"
    volumes:
      - ./:/app
    links:
      - db:db      
    environment:
      -  PHP_MEMORY_LIMIT=-1


  #MySQL Server
  db:
    image: mysql:latest
    container_name: ${DB_CONTAINER_NAME}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"


  #PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PMA_CONTAINER_NAME}
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "8080:80"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini

  
