version: "3"

networks:
  laravel:
    driver: bridge

services:
  #WEB PHP E APACHE
  web:
    container_name: ${WEB_CONTAINER_NAME}
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www/html
    #compartilha um volume para o container
    volumes:
      - "./:/var/www/html/"
    ports:
      - "80:80"
    expose:
      - "9000"
      - "9001"
    #restarta o serviço quando necessário
    restart: always
    environment:
      #altere para o seu endereço IP
      XDEBUG_CONFIG: remote_host=192.168.0.76
    networks:
      - laravel
    links:
      - db:db


  #MySQL Server
  db:
    image: mysql:latest
    container_name: ${DB_CONTAINER_NAME}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - laravel


  #PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PMA_CONTAINER_NAME}
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "8080:80"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    networks:
      - laravel



